apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-phpsidecar
  name: nginx-phpsidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-phpsidecar
  template:
    metadata:
      labels:
        run: nginx-phpsidecar
    spec:
      volumes:
        # Create the shared files volume to be used in both pods
        - name: shared-files
          emptyDir: {}
        
        # Add the ConfigMap we declared above as a volume for the pod
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      containers:
      # Our PHP-FPM application
      - image: dl528888/php_fpm:v1
        name: php-fpm
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/html
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp -r /home/deploy/website/k8s_test/phpsidercar/php_files/ /var/www/html/"]
      - image: nginx:1.7.9
        name: nginx
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/html
          - name: nginx-config-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 20
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 20
      terminationGracePeriodSeconds: 30
